version: 0.2

env:
  shell: bash
  git-credential-helper: "yes"
  variables:
    SAM_VERSION: "1.53.0"
    SAM_CLI_TELEMETRY: "0"

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo "[aws version]"
      - aws --version
      - aws s3 cp ./nested s3://$BUCKET/templates/  --recursive 
      - aws s3 cp main.yaml s3://$BUCKET/templates/ 
      - echo $ENVIRONMENT


  build:
    on-failure: ABORT
    commands:
      - |
        if [ "$ENVIRONMENT" = "dev" ]; then 
          if ! aws cloudformation describe-stacks --stack-name "main-$ENVIRONMENT" ; then
            aws cloudformation create-stack --stack-name main-$ENVIRONMENT --template-url https://$BUCKET.s3.$AWS_REGION.amazonaws.com/templates/main.yaml --parameters file://main-parameters-$ENVIRONMENT.json
            aws cloudformation wait stack-update-complete --stack-name main-$ENVIRONMENT
            echo "Sto facendo la creazione "
          else
            aws cloudformation update-stack --stack-name main-$ENVIRONMENT --template-url https://$BUCKET.s3.$AWS_REGION.amazonaws.com/templates/main.yaml --parameters file://main-parameters-$ENVIRONMENT.json
            aws cloudformation wait stack-update-complete --stack-name main-$ENVIRONMENT
            echo "Sono QUI DENTRO"
          fi
        fi 
        if [ "$ENVIRONEMENT" = "prod" ]; then 
          aws cloudformation update-stack --stack-name main-$ENVIRONMENT --template-url https://$BUCKET.s3.$AWS_REGION.amazonaws.com/templates/main.yaml --parameters file://main-parameters-$ENVIRONMENT.json
          aws cloudformation wait stack-update-complete --stack-name main-$ENVIRONMENT
        fi 
  post_build:
    on-failure: ABORT
    commands:
      - echo "Success"

#  if ["$ENVIRONEMENT" = "prod"]; then 
#           aws cloudformation update-stack --stack-name main-$ENVIRONMENT --template-url https://$BUCKET.s3.$AWS_REGION.amazonaws.com/templates/main.yaml --parameters file://main-parameters-$ENVIRONMENT.json
#           aws cloudformation wait stack-update-complete --stack-name main-$ENVIRONMENT
#         # fi 