AWSTemplateFormatVersion: 2010-09-09
Description: Crea l'infrastruttura
Parameters:
  Project:
    Type: String
    Default: lico2
    Description: Project Name
  CidrBlock:
    Type: String
    Default: 10.49.0.0/16
    Description: VPC CIDR Block
  Environment:
    Type: String
    Default: prod


Resources:

  NetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        ProjectName: !Ref Project
        CidrBlock: !Ref CidrBlock
      Tags: []
      TemplateURL: https://s3templatetestcorley.s3.eu-central-1.amazonaws.com/template/network.yaml
      TimeoutInMinutes: 900

  PrivateSubnetsGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: dbsubnetgroup-tests
      DBSubnetGroupDescription: SubnetGroup for private subnets
      SubnetIds: 
        - "subnet-018c887fd57bd9903"
        - "subnet-054ad9d1676feb5ca"
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-dbsubnetgroup

  MySQLSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: vpc-0d7404eea170ab0a5
      GroupName: !Sub ${Environment}-MySQL-sg
      GroupDescription: !Sub ${Environment}-MySQL-sg


  InboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "All traffic from same SG"
      IpProtocol: -1
      SourceSecurityGroupId: !GetAtt MySQLSG.GroupId
      GroupId: !GetAtt MySQLSG.GroupId


  DBParamUpdate:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: DB Parameter
      Family:  MySQL5.7
      Parameters:
        event_scheduler: 'ON'

  MySQLMaster:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: test
      DBInstanceIdentifier: !Sub "${Environment}-main"
      AutoMinorVersionUpgrade: true
      AllocatedStorage: 100
      # Iops:
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: 5.7
      MasterUsername: admin
      MasterUserPassword: !Sub "{{resolve:secretsmanager:mysql-test:SecretString:DB_PASSWORD}}"
      # EnablePerformanceInsights: true
      # PerformanceInsightsKMSKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsKeyId}"
      # PerformanceInsightsRetentionPeriod: 7
      MultiAZ: false
      DBParameterGroupName: !Ref DBParamUpdate
      #KmsKeyId: !Sub "arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsKeyId}"
      StorageEncrypted: false
      VPCSecurityGroups:
        - !Ref MySQLSG
      DBSubnetGroupName: !Ref PrivateSubnetsGroup
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-main"