AWSTemplateFormatVersion: 2010-09-09
Description: Resource User
Parameters:
  NetworkStackNameParameter:
    Type: String
    Default: network-stack
    Description: Network base stack
  EcsStackNameParameter:
    Type: String
    Default: ecs-cluster
    Description: ECS cluster cloudformation stack name
  ServiceName:
    Type: String
    Default: resource-user
    Description: Your application name (used for lambda functions)
  ServicePort:
    Default: '8081'
    Type: Number
    Description: Your application port
  ServicePriority:
    Default: '2'
    Type: Number
    Description: Application priority
  ServiceHostname:
    Default: user.universe.corley.it
    Type: String
    Description: 'Application domain name. ATTENTION: compatible with PublicHostedZone'
  Registry:
    Type: String
    Description: xxxxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/enetec/user
  Release:
    Type: String
    Default: '1234356'
    Description: Docker image release (TAG)
  ScaleUp:
    Default: '60'
    Type: String
    Description: 'Scale-up on latency [ms]'
  ScaleDown:
    Default: '20'
    Type: String
    Description: 'Scale-down on latency [ms]'
  DesiredCapacity:
    Type: Number
    Default: '1'
    Description: Number of instances to launch in your ECS cluster.
  MaxSize:
    Type: Number
    Default: 5
    Description: Number of max task count
  CPU:
    Type: Number
    Default: 512
    Description: CPU Shares
  Memory:
    Type: Number
    Default: 512
    Description: Memory limit in MB
  AdminPassword:
    Type: String
    NoEcho: 'true'
    Default: admin!!admin!!
    Description: super admin user password
  DatabaseHost:
    Type: String
    Default: ''
    Description: ''
  DatabaseName:
    Type: String
    Default: ''
    Description: ''
  DatabasePassword:
    NoEcho: 'true'
    Type: String
    Default: ''
    Description: ''
  DatabasePort:
    Type: String
    Default: '3306'
    Description: ''
  DatabaseUser:
    Type: String
    Default: 'no'
    Description: ''
  MailerHost:
    Type: String
    Default: 127.0.0.1
    Description: ''
  MailerPassword:
    NoEcho: 'true'
    Type: String
    Default: 'no'
    Description: ''
  MailerTransport:
    Type: String
    Default: smtp
    Description: ''
  MailerUser:
    Type: String
    Default: 'no'
    Description: ''
  PublicKey:
    Type: String
    Default: '%kernel.root_dir%/public.key'
    Description: PublicKey path
  OAuthBaseUrl:
    Type: String
    Default: 'https://auth.lico.corley.it'
    Description: OAuth2 Endpoint
  NotifyToken:
    Type: String
    Default: ''
    Description: Notify API security token
  NotifyBaseUrl:
    Type: String
    Default: 'https://notify.sc365.enetec.info'
    Description: Notify Endpoint
  PublicHostedZone:
    Type: String
    Description: 'Public hosted zone: lico.corley.it'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: App
        Parameters:
          - AdminPassword
          - DatabaseHost
          - DatabaseName
          - DatabasePassword
          - DatabasePort
          - DatabaseUser
          - MailerHost
          - MailerPassword
          - MailerTransport
          - MailerUser
          - PublicKey
    ParameterLabels: {}
Resources:
  AppRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: !Join 
        - ''
        - - !Ref PublicHostedZone
          - .
      Comment: DNS name for app
      Name: !Ref ServiceHostname
      Type: CNAME
      TTL: '300'
      ResourceRecords:
        - !ImportValue 
          'Fn::Sub': '${EcsStackNameParameter}-Endpoint'
  TaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: on-user-signup-sns-notification
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'sns:Publish'
                Resource:
                  - !Ref UserSignupNotification
  UserSignupNotification:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: ResourceUser
      TopicName: ResourceUser
  taskdefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Cpu: !Ref CPU
          Essential: 'true'
          Image: !Join 
            - ':'
            - - !Ref Registry
              - !Ref Release
          Memory: !Ref Memory
          Environment:
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
            - Name: SYMFONY__SECRET
              Value: 31aab925a51b55f6783d13948190d8498df93f71
            - Name: SYMFONY__ADMIN_PASSWORD
              Value: !Ref AdminPassword
            - Name: SYMFONY__DATABASE_HOST
              Value: !Ref DatabaseHost
            - Name: SYMFONY__DATABASE_NAME
              Value: !Ref DatabaseName
            - Name: SYMFONY__DATABASE_PASSWORD
              Value: !Ref DatabasePassword
            - Name: SYMFONY__DATABASE_PORT
              Value: !Ref DatabasePort
            - Name: SYMFONY__DATABASE_USER
              Value: !Ref DatabaseUser
            - Name: SYMFONY__MAILER_HOST
              Value: !Ref MailerHost
            - Name: SYMFONY__MAILER_PASSWORD
              Value: !Ref MailerPassword
            - Name: SYMFONY__MAILER_TRANSPORT
              Value: !Ref MailerTransport
            - Name: SYMFONY__MAILER_USER
              Value: !Ref MailerUser
            - Name: SYMFONY__PUBLIC_KEY
              Value: !Ref PublicKey
            - Name: SYMFONY__USER_SIGNUP_TOPIC_ARN
              Value: !Ref UserSignupNotification
            - Name: SYMFONY__OAUTH_BASE_URL
              Value: !Ref OAuthBaseUrl
            - Name: SYMFONY__NOTIFY_TOKEN
              Value: !Ref NotifyToken
            - Name: SYMFONY__NOTIFY_BASE_URL
              Value: !Ref NotifyBaseUrl
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue 
                'Fn::Sub': '${EcsStackNameParameter}-LogGroupName'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref ServiceName
          MountPoints: []
          PortMappings:
            - HostPort: !Ref ServicePort
              ContainerPort: 80
      Volumes: []
  service:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !ImportValue 
        'Fn::Sub': '${EcsStackNameParameter}-ECSCluster'
      DesiredCount: !Ref DesiredCapacity
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: '80'
          TargetGroupArn: !Ref ECSTG
      Role: !Ref ECSServiceRole
      TaskDefinition: !Ref taskdefinition
  ECSALBListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ECSTG
      Conditions:
        - Field: host-header
          Values:
            - !Ref ServiceHostname
      ListenerArn: !ImportValue 
        'Fn::Sub': '${EcsStackNameParameter}-ALBListener'
      Priority: !Ref ServicePriority
  ECSTG:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 7
      HealthyThresholdCount: 2
      Name: !Ref ServiceName
      Port: !Ref ServicePort
      Protocol: HTTP
      UnhealthyThresholdCount: 10
      VpcId: !ImportValue 
        'Fn::Sub': '${NetworkStackNameParameter}-VpcID'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
  ECSServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: ecs-service
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
                  - 'elasticloadbalancing:DeregisterTargets'
                  - 'elasticloadbalancing:Describe*'
                  - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
                  - 'elasticloadbalancing:RegisterTargets'
                  - 'ec2:Describe*'
                  - 'ec2:AuthorizeSecurityGroupIngress'
                Resource: '*'
  ServiceScalingTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    DependsOn: service
    Properties:
      MaxCapacity: !Ref MaxSize
      MinCapacity: !Ref DesiredCapacity
      ResourceId: !Join 
        - ''
        - - service/
          - !ImportValue 
            'Fn::Sub': '${EcsStackNameParameter}-ECSCluster'
          - /
          - !GetAtt 
            - service
            - Name
      RoleARN: !GetAtt 
        - AutoscalingRole
        - Arn
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: ecs
  ServiceScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: AStepUpPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref ServiceScalingTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: PercentChangeInCapacity
        Cooldown: 60
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 200
  AlarmScaleUp:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: !Ref ScaleUp
      AlarmDescription: Alarm if you service is under stress
      Period: '60'
      AlarmActions:
        - !Ref ServiceScalingPolicy
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !GetAtt 
            - service
            - Name
        - Name: ClusterName
          Value: !ImportValue 
            'Fn::Sub': '${EcsStackNameParameter}-ECSCluster'
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUUtilization
  ServiceScalingDownPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: AStepDownPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref ServiceScalingTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: PercentChangeInCapacity
        Cooldown: 60
        MetricAggregationType: Average
        MinAdjustmentMagnitude: 1
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -50
  AlarmScaleDown:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: !Ref ScaleDown
      AlarmDescription: Alarm if our service is not under stress
      Period: '60'
      AlarmActions:
        - !Ref ServiceScalingDownPolicy
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !GetAtt 
            - service
            - Name
        - Name: ClusterName
          Value: !ImportValue 
            'Fn::Sub': '${EcsStackNameParameter}-ECSCluster'
      ComparisonOperator: LessThanThreshold
      MetricName: CPUUtilization
  AutoscalingRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: service-autoscaling
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'application-autoscaling:*'
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:PutMetricAlarm'
                  - 'ecs:DescribeServices'
                  - 'ecs:UpdateService'
                Resource: '*'
Outputs:
  UserSignupNotification:
    Description: On new user signup notification
    Value: !Ref UserSignupNotification
    Export:
      Name: !Sub '${AWS::StackName}-UserSignupArn'
