AWSTemplateFormatVersion: 2010-09-09
Description: Public frontend application
Parameters:
  BucketName:
    Type: String
    Default: sc365.enetec.info
    Description: You bucket name
  Certificate:
    Type: String
    Default: >-
      arn:aws:acm:us-east-1:379485161710:certificate/9a734fef-74b7-4613-bcf7-919616781a6b
    Description: US (East Virginia) SSL Certificate ARN
  Alias:
    Type: String
    Default: sc365.enetec.info
    Description: 'Aliases separated by ","'
Resources:
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn: S3Bucket
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt 
              - S3Bucket
              - DomainName
            Id: !Ref BucketName
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: 'true'
        Comment: Web App Distribution
        DefaultRootObject: index.html
        Aliases: !Split 
          - ','
          - !Ref Alias
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: !Ref BucketName
          SmoothStreaming: 'false'
          MinTTL: '0'
          MaxTTL: '0'
          DefaultTTL: '0'
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors: []
        CustomErrorResponses: []
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  S3WebsitePolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
            Resource:
              - !Join 
                - ''
                - - !GetAtt 
                    - S3Bucket
                    - Arn
                  - /*

Outputs:
  S3Bucket:
    Value: !Ref S3Bucket